Skip to content
Search or jump toâ€¦

Pull requests
Issues
Marketplace
Explore
 
@mingxiaoyu 
mingxiaoyu
/
N1Openwrt
1
00
 Code Issues 0 Pull requests 0 Actions Projects 0 Wiki Security Insights Settings
N1Openwrt/.github/workflows/n1.yml
@mingxiaoyu mingxiaoyu Update n1.yml
cbcdd63 4 hours ago
145 lines (125 sloc)  4.67 KB
  
#=================================================
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com
#=================================================

name: N1

on:
  push:
    branches: 
      - master
    paths:
      - '.github/workflows/n1.yml'
      - 'ni.config'
  watch:
    types: [started]

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  CONFIG_FILE: ni.config
  DIY_SH: diy.sh
  SSH_ACTIONS: false
  UPLOAD_BIN_DIR: false 
  UPLOAD_FIRMWARE: false
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Clone source code
      run: |
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
        cd openwrt
        useVersionInfo=$(git show -s --date=short --format="Author: %an<br/>date: %cd<br/>commit: %s<br/>commit hash: %H")
        echo "::set-env name=useVersionInfo::$useVersionInfo"
        echo "::set-env name=DATE::$(date "+%Y-%m-%d %H:%M:%S")"
        echo "::set-env name=tag_name::$(date +%Y%m%d)"
        echo "::set-env name=FIRMWARE::$PWD"

    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        name: ${{ env.DATE }} ğŸš€ / N1-Openwrt | ç¼–è¯‘
        allowUpdates: true
        tag: ${{ env.tag_name }}
        commit: master
        token: ${{ secrets.GITHUB_TOKEN  }}
        body: |
          å½“å‰ä½¿ç”¨ç‰ˆæœ¬:ï¼ˆç¼–è¯‘å‰çš„æœ€åä¸€æ¬¡æºç æ›´æ–°è®°å½•ï¼‰
          ${{ env.useVersionInfo }}
        artifacts: "${{ env.FIRMWARE }}/*.tar.gz"  
=
